#ifdef Counters_Module
	.include "AVRModules/Counters/CountersIncludes.inc"
#endif

#ifdef TWSI_Module
	.include "AVRModules/TWSI/TWSI_Includes.inc"
#endif

#ifdef USART_Module
	.include "AVRModules/USART/USART_Includes.inc"
#endif

#ifdef ADC_Module
	.include "AVRModules/ADC/ADCIncludes.inc"
#endif

#ifdef OneWire_Module
	.include "AVRModules/OneWire/OneWire_Includes.inc"
#endif

#ifdef ExternalInterrupts_Module
	.include "AVRModules/ExternalInterrupts/ExtInt_Includes.inc"
#endif
