
#ifdef HD44780U_Module
	.include "GadgetModules/HD44780U/HD44780U_Includes.inc"
#endif

#ifdef RotaryEncoder_Module
	.include "GadgetModules/RotaryEncoder/RotEnc_Includes.inc"
#endif

#ifdef NTC3950_100K_Module
	.include "GadgetModules/NTC3950_100K/NTC3950_100K_Includes.inc"
#endif

#ifdef PCF8575_Module
	.include "GadgetModules/PCF8575/PCF8575_Includes.inc"
#endif

#ifdef PCF8574_Module
	.include "GadgetModules/PCF8574/PCF8574_Includes.inc"
#endif
