
.include "AVRModules/TWSI/TWSI_Const.inc"
.include "AVRModules/Configs/TWSI_Config.inc"

.include "AVRModules/TWSI/TWSI_Times.inc"

.include "AVRModules/TWSI/TWSI_Init.inc"
.include "AVRModules/TWSI/TWSI_ACK_Check.inc"
.include "AVRModules/TWSI/TWSI_TwintFlag.inc"
.include "AVRModules/TWSI/TWSI_ACK_Transmit.inc"
.include "AVRModules/TWSI/TWSI_Start.inc"
.include "AVRModules/TWSI/TWSI_Byte_Transmit.inc"
.include "AVRModules/TWSI/TWSI_Sla.inc"
.include "AVRModules/TWSI/TWSI_Stop.inc"
