.include "Modules/Counters/Counters_Constants.inc"

.include "Modules/Counters/Prescaller/Counters_Prescaller_Counter_0.inc"
.include "Modules/Counters/Prescaller/Counters_Prescaller_Counter_1.inc"
.include "Modules/Counters/Prescaller/Counters_Prescaller_Counter_2.inc"
.include "Modules/Counters/Prescaller/Counters_Prescaller_Counter_3.inc"
.include "Modules/Counters/Prescaller/Counters_Prescaller_Counter_4.inc"
.include "Modules/Counters/Prescaller/Counters_Prescaller_Counter_5.inc"
.include "Modules/Counters/Prescaller/Counters_Prescaller.inc"

.include "Modules/Counters/Counter/Counters_Counter_0.inc"
.include "Modules/Counters/Counter/Counters_Counter_1.inc"
.include "Modules/Counters/Counter/Counters_Counter_2.inc"
.include "Modules/Counters/Counter/Counters_Counter_3.inc"
.include "Modules/Counters/Counter/Counters_Counter_4.inc"
.include "Modules/Counters/Counter/Counters_Counter_5.inc"

.include "Modules/Counters/Counters_Sets.inc"
