.equ Counter0			=	0
.equ Counter1			=	1
.equ Counter2			=	2
.equ Counter3			=	3
.equ Counter4			=	4
.equ Counter5			=	5

.equ mks1			=	0
.equ mks10			=	1
.equ mks25			=	2
.equ mks100			=	3
.equ Overflow		=	5
.equ CompareMatch	=	6
.equ CompareMatchA	=	7
.equ CompareMatchB	=	8




//.equ ms500			=	9
//.equ s1				=	10


.equ Prescaller1	=	1
.equ Prescaller8	=	8
.equ Prescaller32	=	32
.equ Prescaller64	=	64
.equ Prescaller128	=	128
.equ Prescaller256	=	256
.equ Prescaller1024	=	1024
