.equ Counter0		=	0
.equ Counter1		=	1
.equ Counter2		=	2
.equ Counter3		=	3
.equ Counter4		=	4
.equ Counter5		=	5

.equ Overflow		=	6
.equ CompareMatch	=	7
.equ CompareMatchA	=	8
.equ CompareMatchB	=	9




//.equ ms500			=	9
//.equ s1				=	10


.equ Prescaller1	=	1
.equ Prescaller8	=	8
.equ Prescaller32	=	32
.equ Prescaller64	=	64
.equ Prescaller128	=	128
.equ Prescaller256	=	256
.equ Prescaller1024	=	1024
