
.include "Modules/TWSI/TWSI_Const.inc"
.include "Modules/Configs/TWSI_Config.inc"

.include "Modules/TWSI/TWSI_Times.inc"

.include "Modules/TWSI/TWSI_Init.inc"
.include "Modules/TWSI/TWSI_TwiStatus.inc"
.include "Modules/TWSI/TWSI_TwintFlag.inc"
.include "Modules/TWSI/TWSI_Nack.inc"
.include "Modules/TWSI/TWSI_Start.inc"
.include "Modules/TWSI/TWSI_SendingByte.inc"
.include "Modules/TWSI/TWSI_ReadingByte.inc"
.include "Modules/TWSI/TWSI_Sla.inc"
.include "Modules/TWSI/TWSI_Stop.inc"
