// Analog Comparator Handler
ANA_COMP:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// ADC Conversion Complete Handler
ADC_Conv_Comp:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
//EEPROM Ready Handler
EE_RDY:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// External Interrupts
EXT_INT0:
	cli
	// Ваш код
	sei
reti
EXT_INT1:
	cli
	// Ваш код
	sei
reti
EXT_INT2:
	cli
	// Ваш код
	sei
reti
EXT_INT3:
	cli
	// Ваш код
	sei
reti
EXT_INT4:
	cli
	// Ваш код
	sei
reti
EXT_INT5:
	cli
	// Ваш код
	//Clear_INT_Interrupt INT5
	//PCF8575_Read $40

	//Set_INT_Interrupt INT5, FallingEdge
	sei
reti
EXT_INT6:
	cli
	// Ваш код
	sei
reti
EXT_INT7:
	cli
	// Ваш код
	sei
reti
EXT_PCINT0:
	cli
	// Ваш код
	sei
reti
EXT_PCINT1:
	cli
	// Ваш код
	sei
reti
EXT_PCINT2:
	cli
	// Ваш код
	sei
ret
EXT_PCINT3:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// LCD_SOF
LCD_SOF:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// SPI
SPI_STC:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// SPM_RDY
SPM_RDY:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// Timer 0
TIM0_COMP:
	cli
	// Ваш код
	sei
reti
TIM0_COMPA:
	cli
	// Ваш код
	sei
reti
TIM0_COMPB:
	cli
	// Ваш код
	sei
reti
TIM0_OVF:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// Timer 1
TIM1_CAPT:
	cli
	// Ваш код
	sei
reti
TIM1_COMPA:
	cli
	// Ваш код
	sei
reti
TIM1_COMPB:
	cli
	// Ваш код
	sei
reti
TIM1_COMPC:
	cli
	// Ваш код
	sei
reti
TIM1_OVF:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// Timer 2
TIM2_COMP:
	cli
	// Ваш код
	sei
reti
TIM2_COMPA:
	cli
	// Ваш код
	sei
reti
TIM2_COMPB:
	cli
	// Ваш код
	sei
reti
TIM2_OVF:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
//Timer 3
TIM3_CAPT:
	cli
	// Ваш код
	sei
reti
TIM3_COMPA:
	cli
	// Ваш код
	sei
reti
TIM3_COMPB:
	cli
	// Ваш код
	sei
reti
TIM3_COMPC:
	cli
	// Ваш код
	sei
reti
TIM3_OVF:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// Timer 4
TIM4_CAPT:
	cli
	// Ваш код
	sei
reti
TIM4_COMPA:
	cli
	// Ваш код
	sei
reti
TIM4_COMPB:
	cli
	// Ваш код
	sei
reti
TIM4_COMPC:
	cli
	// Ваш код
	sei
reti
TIM4_OVF:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// Timer 5
TIM5_CAPT:
	cli
	// Ваш код
	sei
reti
TIM5_COMPA:
	cli
	// Ваш код
	sei
reti
TIM5_COMPB:
	cli
	// Ваш код
	sei
reti
TIM5_COMPC:
	cli
	// Ваш код
	sei
reti
TIM5_OVF:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// TWSI
TWSI:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// USART
USART0_RXC:
	cli
	// Ваш код
	sei
reti
USART0_UDRE:
	cli
	// Ваш код
	sei
reti
USART0_TXC:
	cli
	// Ваш код
	sei
reti
USART1_RXC:
	cli
	// Ваш код
	sei
reti
USART1_UDRE:
	cli
	// Ваш код
	sei
reti
USART1_TXC:
	cli
	// Ваш код
	sei
reti
USART2_RXC:
	cli
	// Ваш код
	sei
reti
USART2_UDRE:
	cli
	// Ваш код
	sei
reti
USART2_TXC:
	cli
	// Ваш код
	sei
reti

USART3_RXC:
	cli
	// Ваш код
	sei
reti
USART3_UDRE:
	cli
	// Ваш код
	sei
reti
USART3_TXC:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
//USI
USI_STRT:
	cli
	// Ваш код
	sei
reti
USI_OVFL:
	cli
	// Ваш код
	sei
reti
////////////////////////////////////////////////////////////
// WDT
WDT:
	cli
	// Ваш код
	sei
reti
