
CountersPrescaller Counter0, Prescaller8
CountersPrescaller Counter1, Prescaller1024
CountersPrescaller Counter2, Prescaller8
CountersPrescaller Counter3, Prescaller8
CountersPrescaller Counter4, Prescaller1024
CountersPrescaller Counter5, Prescaller1024

CounterInterrupt Counter0, Overflow, enabled
//CounterInterrupt Counter0, CompareMatch, enabled
CounterInterrupt Counter0, CompareMatchA, enabled
CounterInterrupt Counter0, CompareMatchB, enabled
CounterInterrupt Counter5, CaptureEvent, enabled
CounterInterrupt Counter5, Overflow, enabled
//CounterInterrupt Counter5, CompareMatch, enabled
CounterInterrupt Counter5, CompareMatchA, enabled
CounterInterrupt Counter5, CompareMatchB, enabled
CounterInterrupt Counter5, CompareMatchC, enabled
