
CountersPrescaller Counter0, Prescaller8
CountersPrescaller Counter1, Prescaller1024
CountersPrescaller Counter2, Prescaller8
CountersPrescaller Counter3, Prescaller8
CountersPrescaller Counter4, Prescaller1024
CountersPrescaller Counter5, Prescaller1024

//CounterInterrupt Counter0, Overflow, enabled
//CounterInterrupt Counter0, CompareMatch, enabled
//CounterInterrupt Counter0, CompareMatchA, enabled
//CounterInterrupt Counter0, CompareMatchB, enabled
//CounterInterrupt Counter5, CaptureEvent, enabled
//CounterInterrupt Counter5, Overflow, enabled
//CounterInterrupt Counter5, CompareMatch, enabled
//CounterInterrupt Counter5, CompareMatchA, enabled
//CounterInterrupt Counter5, CompareMatchB, enabled
//CounterInterrupt Counter5, CompareMatchC, enabled

//WeveformGenerationMode Counter0, 2
//WeveformGenerationMode Counter1, 2
//WeveformGenerationMode Counter2, 2
//WeveformGenerationMode Counter3, 2
//WeveformGenerationMode Counter4, 2
WeveformGenerationMode Counter5, 12

//CompareOutputMode Counter5, CompareMatchOutput, 3
//CompareOutputMode Counter5, CompareMatchOutputC, 3
//CompareOutputMode Counter5, CompareMatchOutputA, 3
//CompareOutputMode Counter5, CompareMatchOutputB, 3
