
.include "AVRModules/ADC/ADC_Constants.inc"
.include "AVRModules/Configs/ADC_Config.inc"

.include "AVRModules/ADC/ADC_Prescaler.inc"
.include "AVRModules/ADC/ADC_ReferenceSelection.inc"
.include "AVRModules/ADC/ADC_LeftAdjustResult.inc"
.include "AVRModules/ADC/ADC_ChannelSelection.inc"
.include "AVRModules/ADC/ADC_Mode.inc"
.include "AVRModules/ADC/ADC_Interrupt.inc"
.include "AVRModules/ADC/ADC_DigitalInputDisable.inc"

.include "AVRModules/ADC/ADC_Init.inc"
.include "AVRModules/ADC/ADC_START.inc"
