
.equ FreeRun		=	0
.equ AnComp			=	1
.equ ExtIntReq0		=	2
.equ TC0CompMatch	=	3
.equ TC0Overflow	=	4
.equ TC1CompMatchB	=	5
.equ TC1Overflow	=	6
.equ TC1CaptEvent	=	7

.equ ADC0			=	8
.equ ADC1			=	9
.equ ADC2			=	10
.equ ADC3			=	11
.equ ADC4			=	12
.equ ADC5			=	13
.equ ADC6			=	14
.equ ADC7			=	15
.equ ADC8			=	16
.equ ADC9			=	17
.equ ADC10			=	18
.equ ADC11			=	19
.equ ADC12			=	20
.equ ADC13			=	21
.equ ADC14			=	22
.equ ADC15			=	23
.equ V0				=	24
.equ V1				=	25
