
.include "AVRModules/ADC/ADCConstants.inc"
.include "AVRModules/ADC/ADCPrescalerSelection.inc"
.include "AVRModules/ADC/ADCInputChannelSelection.inc"
.include "AVRModules/ADC/ADCDigitalInputDisable.inc"
.include "AVRModules/Configs/ADC_Config.inc"

.include "AVRModules/ADC/ADC_ReferenceSelection.inc"
.include "AVRModules/ADC/ADC_LeftAdjustResult.inc"
.include "AVRModules/ADC/ADC_Mode.inc"
.include "AVRModules/ADC/ADC_Interrupt.inc"

.include "AVRModules/ADC/ADC_Init.inc"
.include "AVRModules/ADC/ADC_START.inc"
