
.include "AVRModules/ADC/ADCConstants.inc"
.include "AVRModules/ADC/ADCPrescalerSelection.inc"
.include "AVRModules/ADC/ADCInputChannelSelection.inc"
.include "AVRModules/ADC/ADCDigitalInputDisable.inc"
.include "AVRModules/ADC/ADCReferenceSelection.inc"
.include "AVRModules/ADC/ADCLeftAdjustResult.inc"
.include "AVRModules/ADC/ADCAutoTriggerSourceSelections.inc"
.include "AVRModules/ADC/ADCInterrupt.inc"

.include "AVRModules/ADC/ADCCondition.inc"
.include "AVRModules/ADC/ADCConversion.inc"
